"""Tests for GitHub PR annotation integration."""

from depfence.core.models import Finding, FindingType, PackageId, ScanResult, Severity
from depfence.integrations.github_pr import format_pr_comment


def _make_result(findings=None, packages_scanned=10):
    result = ScanResult(target="/tmp/test", ecosystem="npm")
    result.findings = findings or []
    result.packages_scanned = packages_scanned
    return result


def _make_finding(severity=Severity.HIGH, fix_version=None):
    return Finding(
        finding_type=FindingType.KNOWN_VULN,
        severity=severity,
        package="npm:lodash@4.17.20",
        title="Prototype pollution",
        detail="Allows property injection",
        fix_version=fix_version,
    )


def test_clean_scan():
    result = _make_result()
    comment = format_pr_comment(result)
    assert "No security issues" in comment
    assert ":white_check_mark:" in comment


def test_critical_findings():
    result = _make_result([_make_finding(Severity.CRITICAL)])
    comment = format_pr_comment(result)
    assert "CRITICAL" in comment
    assert ":x:" in comment
    assert "lodash" in comment


def test_high_findings():
    result = _make_result([_make_finding(Severity.HIGH)])
    comment = format_pr_comment(result)
    assert "WARN" in comment
    assert ":warning:" in comment


def test_severity_table():
    findings = [
        _make_finding(Severity.CRITICAL),
        _make_finding(Severity.HIGH),
        _make_finding(Severity.MEDIUM),
    ]
    result = _make_result(findings)
    comment = format_pr_comment(result)
    assert "| :red_circle: Critical | 1 |" in comment
    assert "| :orange_circle: High | 1 |" in comment


def test_diff_info():
    result = _make_result([_make_finding()])
    comment = format_pr_comment(result, diff_info={"added": 3})
    assert "3 new dependencies" in comment


def test_fixable_findings():
    result = _make_result([_make_finding(fix_version="4.17.21")])
    comment = format_pr_comment(result)
    assert "auto-fix" in comment.lower()
    assert "depfence fix" in comment


def test_generated_by_footer():
    result = _make_result([_make_finding()])
    comment = format_pr_comment(result)
    assert "depfence" in comment
    assert "Generated by" in comment
