"""Tests for depfence/parsers/cargo_lockfile.py."""

from __future__ import annotations

from pathlib import Path

from depfence.core.models import PackageId
from depfence.parsers.cargo_lockfile import _parse_blocks, parse_cargo_lock

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

CARGO_LOCK_V1 = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "serde"
version = "1.0.160"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb2f3770ded5b0f5929b73094f85fcba14c3abc"

[[package]]
name = "serde_json"
version = "1.0.96"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "057d394a50403bcac12672b2b18fb387ab"
dependencies = [
 "serde",
]

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "serde",
 "serde_json",
]
"""

CARGO_LOCK_V3 = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.71"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9c7d0618f0e0b7e8ff11427422b"

[[package]]
name = "tokio"
version = "1.28.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5a4b8ab5c1a3d3"
dependencies = [
 "anyhow",
]

[[package]]
name = "myservice"
version = "0.2.0"
dependencies = [
 "anyhow",
 "tokio",
]
"""

CARGO_LOCK_EMPTY = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
"""

CARGO_LOCK_NO_VERSION = """\
[[package]]
name = "orphan"
"""

CARGO_LOCK_ONLY_WORKSPACE_ROOT = """\
[[package]]
name = "workspace-root"
version = "0.0.0"
"""

CARGO_LOCK_LARGE = """\
[[package]]
name = "pkg-a"
version = "1.0.0"

[[package]]
name = "pkg-b"
version = "2.0.0"

[[package]]
name = "pkg-c"
version = "3.0.0"

[[package]]
name = "pkg-d"
version = "4.0.0"

[[package]]
name = "pkg-e"
version = "5.0.0"
"""

CARGO_LOCK_MISSING_NAME = """\
[[package]]
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"""

CARGO_LOCK_MULTIPLE_SAME_NAME_DIFF_VERSION = """\
[[package]]
name = "common-dep"
version = "1.0.0"

[[package]]
name = "common-dep"
version = "2.0.0"
"""


# ---------------------------------------------------------------------------
# Tests for _parse_blocks (internal helper)
# ---------------------------------------------------------------------------

class TestParseBlocks:
    def test_empty_text_returns_empty_list(self):
        assert _parse_blocks("") == []

    def test_single_block_parsed(self):
        blocks = _parse_blocks('[[package]]\nname = "foo"\nversion = "1.0.0"\n')
        assert len(blocks) == 1
        assert blocks[0]["name"] == "foo"
        assert blocks[0]["version"] == "1.0.0"

    def test_multiple_blocks_parsed(self):
        blocks = _parse_blocks(CARGO_LOCK_V1)
        assert len(blocks) == 3

    def test_array_valued_keys_ignored(self):
        # dependencies = [ ... ] uses a different syntax — _KV_RE won't match it
        blocks = _parse_blocks(CARGO_LOCK_V1)
        for block in blocks:
            assert "dependencies" not in block

    def test_first_occurrence_of_key_kept(self):
        # If a key appears twice (pathological), only the first value is kept.
        text = '[[package]]\nname = "first"\nname = "second"\n'
        blocks = _parse_blocks(text)
        assert blocks[0]["name"] == "first"


# ---------------------------------------------------------------------------
# Tests for parse_cargo_lock
# ---------------------------------------------------------------------------

class TestParseCargoLockV1:
    def test_package_count(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        packages = parse_cargo_lock(lock)
        assert len(packages) == 3

    def test_names_extracted(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        names = {p.name for p in parse_cargo_lock(lock)}
        assert names == {"serde", "serde_json", "myapp"}

    def test_versions_extracted(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        by_name = {p.name: p for p in parse_cargo_lock(lock)}
        assert by_name["serde"].version == "1.0.160"
        assert by_name["serde_json"].version == "1.0.96"
        assert by_name["myapp"].version == "0.1.0"

    def test_ecosystem_is_cargo(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        assert all(p.ecosystem == "cargo" for p in parse_cargo_lock(lock))

    def test_returns_package_id_instances(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        assert all(isinstance(p, PackageId) for p in parse_cargo_lock(lock))


class TestParseCargoLockV3:
    def test_package_count(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V3)
        assert len(parse_cargo_lock(lock)) == 3

    def test_names_extracted(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V3)
        names = {p.name for p in parse_cargo_lock(lock)}
        assert names == {"anyhow", "tokio", "myservice"}

    def test_versions_extracted(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V3)
        by_name = {p.name: p for p in parse_cargo_lock(lock)}
        assert by_name["anyhow"].version == "1.0.71"
        assert by_name["tokio"].version == "1.28.2"
        assert by_name["myservice"].version == "0.2.0"

    def test_version_3_preamble_not_parsed_as_package(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V3)
        names = {p.name for p in parse_cargo_lock(lock)}
        # "version = 3" is a top-level key, not inside [[package]]; must not appear
        assert "version" not in names


class TestParseCargoLockEdgeCases:
    def test_empty_file_returns_empty_list(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_EMPTY)
        assert parse_cargo_lock(lock) == []

    def test_block_without_name_skipped(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_MISSING_NAME)
        assert parse_cargo_lock(lock) == []

    def test_block_without_version_has_none_version(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_NO_VERSION)
        packages = parse_cargo_lock(lock)
        assert len(packages) == 1
        assert packages[0].name == "orphan"
        assert packages[0].version is None

    def test_multiple_versions_of_same_package(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_MULTIPLE_SAME_NAME_DIFF_VERSION)
        packages = parse_cargo_lock(lock)
        assert len(packages) == 2
        versions = {p.version for p in packages}
        assert versions == {"1.0.0", "2.0.0"}

    def test_only_workspace_root(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_ONLY_WORKSPACE_ROOT)
        packages = parse_cargo_lock(lock)
        assert len(packages) == 1
        assert packages[0].name == "workspace-root"

    def test_large_lockfile(self, tmp_path: Path):
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_LARGE)
        packages = parse_cargo_lock(lock)
        assert len(packages) == 5
        names = {p.name for p in packages}
        assert "pkg-a" in names
        assert "pkg-e" in names

    def test_preserves_hyphenated_names(self, tmp_path: Path):
        content = '[[package]]\nname = "my-crate-name"\nversion = "0.1.0"\n'
        lock = tmp_path / "Cargo.lock"
        lock.write_text(content)
        packages = parse_cargo_lock(lock)
        assert packages[0].name == "my-crate-name"

    def test_unicode_safe(self, tmp_path: Path):
        # Cargo names are ASCII-only but comments may have unicode
        content = "# Généré automatiquement\n[[package]]\nname = \"hello\"\nversion = \"1.0.0\"\n"
        lock = tmp_path / "Cargo.lock"
        lock.write_text(content, encoding="utf-8")
        packages = parse_cargo_lock(lock)
        assert len(packages) == 1
        assert packages[0].name == "hello"
