"""Tests for Cargo and Go parser modules."""

from __future__ import annotations

from pathlib import Path

import pytest

from depfence.parsers.cargo_lockfile import parse_cargo_lock
from depfence.parsers.go_sum import parse_go_mod, parse_go_sum


# ---------------------------------------------------------------------------
# Cargo.lock fixtures
# ---------------------------------------------------------------------------

CARGO_LOCK_V1 = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "serde"
version = "1.0.160"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bb2f3770ded5b0f5929b73094f85fcba14c3"

[[package]]
name = "serde_json"
version = "1.0.96"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "057d394a50403bcac12672b2b18fb387ab"
dependencies = [
 "serde",
]

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "serde",
 "serde_json",
]
"""

CARGO_LOCK_V3 = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.71"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9c7d0618f0e0b7e8ff11427422b"

[[package]]
name = "tokio"
version = "1.28.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "5a4b8ab5c1a3d3"
dependencies = [
 "anyhow",
]

[[package]]
name = "myservice"
version = "0.2.0"
dependencies = [
 "anyhow",
 "tokio",
]
"""

CARGO_LOCK_EMPTY = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
"""

CARGO_LOCK_NO_VERSION = """\
[[package]]
name = "orphan"
"""


# ---------------------------------------------------------------------------
# go.sum fixtures
# ---------------------------------------------------------------------------

GO_SUM_CONTENT = """\
github.com/pkg/errors v0.9.0 h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt38=
github.com/pkg/errors v0.9.0/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl08=
golang.org/x/sync v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
golang.org/x/sync v0.3.0/go.mod h1:FU7BRWMLTJDbd2wh6sVrkAa1tFfmZQ5kX/vTovp/gjM=
github.com/stretchr/testify v1.8.3 h1:RP3t2pwF7cMEbC1dqtB6poj3niw/9gnV4Cjg5oW5Oiw=
github.com/stretchr/testify v1.8.3/go.mod h1:sz/lmYIOXD/1dqDmKjjqLyZ2RngseejIcXlSw2iwfAo=
"""

GO_SUM_MALFORMED = """\
# this line is a comment
github.com/foo/bar v1.0.0 h1:abcdef=
github.com/bad line without hash

github.com/another/pkg v2.0.0/go.mod h1:xyz=
github.com/another/pkg v2.0.0 h1:xyz=
"""

GO_SUM_EMPTY = ""

# ---------------------------------------------------------------------------
# go.mod fixtures
# ---------------------------------------------------------------------------

GO_MOD_CONTENT = """\
module example.com/myapp

go 1.21

require (
\tgithub.com/gin-gonic/gin v1.9.1
\tgithub.com/pkg/errors v0.9.0
\tgolang.org/x/sync v0.3.0 // indirect
)

require github.com/stretchr/testify v1.8.3
"""

GO_MOD_EMPTY_REQUIRE = """\
module example.com/empty

go 1.21

require (
)
"""

GO_MOD_NO_REQUIRE = """\
module example.com/minimal

go 1.21
"""

GO_MOD_WITH_COMMENTS = """\
module example.com/commented

go 1.21

require (
\t// this whole line is a comment
\tgithub.com/real/dep v1.0.0
)
"""


# ---------------------------------------------------------------------------
# TestCargoLock
# ---------------------------------------------------------------------------


class TestCargoLock:
    def test_v1_basic_parsing(self, tmp_path: Path) -> None:
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        packages = parse_cargo_lock(lock)

        assert len(packages) == 3
        names = {p.name for p in packages}
        assert names == {"serde", "serde_json", "myapp"}
        for p in packages:
            assert p.ecosystem == "cargo"

    def test_v1_versions(self, tmp_path: Path) -> None:
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        packages = parse_cargo_lock(lock)

        by_name = {p.name: p for p in packages}
        assert by_name["serde"].version == "1.0.160"
        assert by_name["serde_json"].version == "1.0.96"
        assert by_name["myapp"].version == "0.1.0"

    def test_v3_format(self, tmp_path: Path) -> None:
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V3)
        packages = parse_cargo_lock(lock)

        assert len(packages) == 3
        names = {p.name for p in packages}
        assert names == {"anyhow", "tokio", "myservice"}

    def test_v3_versions(self, tmp_path: Path) -> None:
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V3)
        packages = parse_cargo_lock(lock)

        by_name = {p.name: p for p in packages}
        assert by_name["anyhow"].version == "1.0.71"
        assert by_name["tokio"].version == "1.28.2"

    def test_empty_file(self, tmp_path: Path) -> None:
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_EMPTY)
        packages = parse_cargo_lock(lock)
        assert packages == []

    def test_entry_without_version(self, tmp_path: Path) -> None:
        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_NO_VERSION)
        packages = parse_cargo_lock(lock)
        assert len(packages) == 1
        assert packages[0].name == "orphan"
        assert packages[0].version is None

    def test_returns_package_id_type(self, tmp_path: Path) -> None:
        from depfence.core.models import PackageId

        lock = tmp_path / "Cargo.lock"
        lock.write_text(CARGO_LOCK_V1)
        packages = parse_cargo_lock(lock)
        assert all(isinstance(p, PackageId) for p in packages)


# ---------------------------------------------------------------------------
# TestGoSum
# ---------------------------------------------------------------------------


class TestGoSum:
    def test_basic_parsing(self, tmp_path: Path) -> None:
        gosum = tmp_path / "go.sum"
        gosum.write_text(GO_SUM_CONTENT)
        packages = parse_go_sum(gosum)

        # 3 unique (module, version) pairs — /go.mod lines are deduplicated
        assert len(packages) == 3
        names = {p.name for p in packages}
        assert "github.com/pkg/errors" in names
        assert "golang.org/x/sync" in names
        assert "github.com/stretchr/testify" in names

    def test_ecosystem(self, tmp_path: Path) -> None:
        gosum = tmp_path / "go.sum"
        gosum.write_text(GO_SUM_CONTENT)
        packages = parse_go_sum(gosum)
        assert all(p.ecosystem == "go" for p in packages)

    def test_version_stripped(self, tmp_path: Path) -> None:
        gosum = tmp_path / "go.sum"
        gosum.write_text(GO_SUM_CONTENT)
        packages = parse_go_sum(gosum)

        by_name = {p.name: p for p in packages}
        # Version must NOT contain /go.mod
        assert by_name["github.com/pkg/errors"].version == "v0.9.0"

    def test_deduplication(self, tmp_path: Path) -> None:
        # Both the hash line and the /go.mod line for the same version must
        # collapse into a single PackageId.
        content = (
            "github.com/foo/bar v1.0.0 h1:aaa=\n"
            "github.com/foo/bar v1.0.0/go.mod h1:bbb=\n"
        )
        gosum = tmp_path / "go.sum"
        gosum.write_text(content)
        packages = parse_go_sum(gosum)
        assert len(packages) == 1
        assert packages[0].name == "github.com/foo/bar"
        assert packages[0].version == "v1.0.0"

    def test_malformed_lines_skipped(self, tmp_path: Path) -> None:
        gosum = tmp_path / "go.sum"
        gosum.write_text(GO_SUM_MALFORMED)
        packages = parse_go_sum(gosum)
        # The malformed line "github.com/bad line without hash" should be skipped.
        # Valid lines: github.com/foo/bar v1.0.0, github.com/another/pkg v2.0.0
        names = {p.name for p in packages}
        assert "github.com/bad" not in names
        assert "github.com/foo/bar" in names
        assert "github.com/another/pkg" in names

    def test_empty_file(self, tmp_path: Path) -> None:
        gosum = tmp_path / "go.sum"
        gosum.write_text(GO_SUM_EMPTY)
        packages = parse_go_sum(gosum)
        assert packages == []


# ---------------------------------------------------------------------------
# TestGoMod
# ---------------------------------------------------------------------------


class TestGoMod:
    def test_basic_parsing(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_CONTENT)
        packages = parse_go_mod(gomod)

        names = {p.name for p in packages}
        assert "github.com/gin-gonic/gin" in names
        assert "github.com/pkg/errors" in names
        assert "golang.org/x/sync" in names
        assert "github.com/stretchr/testify" in names

    def test_ecosystem(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_CONTENT)
        packages = parse_go_mod(gomod)
        assert all(p.ecosystem == "go" for p in packages)

    def test_versions(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_CONTENT)
        packages = parse_go_mod(gomod)

        by_name = {p.name: p for p in packages}
        assert by_name["github.com/gin-gonic/gin"].version == "v1.9.1"
        assert by_name["golang.org/x/sync"].version == "v0.3.0"
        assert by_name["github.com/stretchr/testify"].version == "v1.8.3"

    def test_indirect_comment_stripped(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_CONTENT)
        packages = parse_go_mod(gomod)

        by_name = {p.name: p for p in packages}
        # The "// indirect" comment must not bleed into the version string
        assert by_name["golang.org/x/sync"].version == "v0.3.0"

    def test_empty_require_block(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_EMPTY_REQUIRE)
        packages = parse_go_mod(gomod)
        assert packages == []

    def test_no_require_directives(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_NO_REQUIRE)
        packages = parse_go_mod(gomod)
        assert packages == []

    def test_comment_lines_inside_block_skipped(self, tmp_path: Path) -> None:
        gomod = tmp_path / "go.mod"
        gomod.write_text(GO_MOD_WITH_COMMENTS)
        packages = parse_go_mod(gomod)
        assert len(packages) == 1
        assert packages[0].name == "github.com/real/dep"

    def test_go_toolchain_line_skipped(self, tmp_path: Path) -> None:
        content = """\
module example.com/tool

go 1.21

require (
\tgo 1.21
\tgithub.com/real/dep v1.0.0
)
"""
        gomod = tmp_path / "go.mod"
        gomod.write_text(content)
        packages = parse_go_mod(gomod)
        names = {p.name for p in packages}
        assert "go" not in names
        assert "github.com/real/dep" in names
