"""Tests for Dart/Flutter pubspec.lock and pubspec.yaml parsers."""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from depfence.core.models import PackageId
from depfence.parsers.pubspec_lockfile import parse_pubspec_lock, parse_pubspec_yaml


PUBSPEC_LOCK_FIXTURE = """\
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "abc123"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  meta:
    dependency: "direct main"
    description:
      name: meta
      sha256: "def456"
      url: "https://pub.dev"
    source: hosted
    version: "1.15.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "ghi789"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: "jkl012"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
sdks:
  dart: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
"""

PUBSPEC_YAML_FIXTURE = """\
name: my_app
description: A sample Flutter app
version: 1.0.0

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ">=6.0.0"
  cached_network_image: any
  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ">=5.4.0"

flutter:
  uses-material-design: true
"""

PUBSPEC_LOCK_EMPTY = """\
# Generated by pub
packages:
sdks:
  dart: ">=3.0.0 <4.0.0"
"""


class TestParsePubspecLock:
    def test_parses_all_packages(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".lock", delete=False) as f:
            f.write(PUBSPEC_LOCK_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_lock(path)
        assert len(pkgs) == 4
        names = {p.name for p in pkgs}
        assert names == {"http", "meta", "path", "flutter_lints"}

    def test_correct_ecosystem(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".lock", delete=False) as f:
            f.write(PUBSPEC_LOCK_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_lock(path)
        assert all(p.ecosystem == "dart" for p in pkgs)

    def test_correct_versions(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".lock", delete=False) as f:
            f.write(PUBSPEC_LOCK_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_lock(path)
        version_map = {p.name: p.version for p in pkgs}
        assert version_map["http"] == "1.2.0"
        assert version_map["meta"] == "1.15.0"
        assert version_map["path"] == "1.9.0"
        assert version_map["flutter_lints"] == "3.0.2"

    def test_empty_lockfile(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".lock", delete=False) as f:
            f.write(PUBSPEC_LOCK_EMPTY)
            path = Path(f.name)
        pkgs = parse_pubspec_lock(path)
        assert pkgs == []


class TestParsePubspecYaml:
    def test_parses_dependencies(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write(PUBSPEC_YAML_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_yaml(path)
        names = {p.name for p in pkgs}
        assert "http" in names
        assert "provider" in names
        assert "cached_network_image" in names
        assert "cupertino_icons" in names

    def test_parses_dev_dependencies(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write(PUBSPEC_YAML_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_yaml(path)
        names = {p.name for p in pkgs}
        assert "flutter_lints" in names
        assert "mockito" in names

    def test_skips_sdk_deps(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write(PUBSPEC_YAML_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_yaml(path)
        names = {p.name for p in pkgs}
        assert "flutter" not in names
        assert "flutter_test" not in names

    def test_correct_ecosystem(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write(PUBSPEC_YAML_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_yaml(path)
        assert all(p.ecosystem == "dart" for p in pkgs)

    def test_version_extraction(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write(PUBSPEC_YAML_FIXTURE)
            path = Path(f.name)
        pkgs = parse_pubspec_yaml(path)
        version_map = {p.name: p.version for p in pkgs}
        assert version_map["http"] == "1.2.0"
        assert version_map["cupertino_icons"] == "1.0.8"


class TestLockfileDiscovery:
    def test_discovers_pubspec_lock(self):
        from depfence.core.lockfile import detect_ecosystem
        with tempfile.TemporaryDirectory() as d:
            p = Path(d)
            (p / "pubspec.lock").write_text(PUBSPEC_LOCK_FIXTURE)
            result = detect_ecosystem(p)
            ecosystems = [eco for eco, _ in result]
            assert "dart" in ecosystems

    def test_discovers_pom_xml(self):
        from depfence.core.lockfile import detect_ecosystem
        with tempfile.TemporaryDirectory() as d:
            p = Path(d)
            (p / "pom.xml").write_text("<project/>")
            result = detect_ecosystem(p)
            ecosystems = [eco for eco, _ in result]
            assert "maven" in ecosystems

    def test_discovers_packages_config(self):
        from depfence.core.lockfile import detect_ecosystem
        with tempfile.TemporaryDirectory() as d:
            p = Path(d)
            (p / "packages.config").write_text('<packages/>')
            result = detect_ecosystem(p)
            ecosystems = [eco for eco, _ in result]
            assert "nuget" in ecosystems

    def test_discovers_version_catalog(self):
        from depfence.core.lockfile import detect_ecosystem
        with tempfile.TemporaryDirectory() as d:
            p = Path(d)
            gradle_dir = p / "gradle"
            gradle_dir.mkdir()
            (gradle_dir / "libs.versions.toml").write_text("[libraries]")
            result = detect_ecosystem(p)
            ecosystems = [eco for eco, _ in result]
            assert "maven" in ecosystems

    def test_parse_lockfile_dispatches_dart(self):
        from depfence.core.lockfile import parse_lockfile
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".lock", prefix="pubspec", delete=False
        ) as f:
            f.write(PUBSPEC_LOCK_FIXTURE)
            path = Path(f.name)
        # Rename to pubspec.lock for dispatch
        target = path.parent / "pubspec.lock"
        path.rename(target)
        pkgs = parse_lockfile("dart", target)
        assert len(pkgs) == 4
        assert all(p.ecosystem == "dart" for p in pkgs)

    def test_parse_lockfile_dispatches_version_catalog(self):
        from depfence.core.lockfile import parse_lockfile
        catalog = """\
[versions]
gson = "2.10.1"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
"""
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".toml", prefix="libs.versions", delete=False
        ) as f:
            f.write(catalog)
            path = Path(f.name)
        target = path.parent / "libs.versions.toml"
        path.rename(target)
        pkgs = parse_lockfile("maven", target)
        assert len(pkgs) == 1
        assert pkgs[0].name == "com.google.code.gson:gson"
        assert pkgs[0].version == "2.10.1"
