"""GitHub PR annotation — post inline comments with dependency risk info.

Used in CI to annotate PRs with security findings for each changed dependency.
Requires GITHUB_TOKEN environment variable with appropriate permissions.
"""

from __future__ import annotations

from depfence.core.models import ScanResult, Severity


def format_pr_comment(result: ScanResult, diff_info: dict | None = None) -> str:
    """Format scan results as a GitHub PR comment body."""
    critical = sum(1 for f in result.findings if f.severity == Severity.CRITICAL)
    high = sum(1 for f in result.findings if f.severity == Severity.HIGH)
    medium = sum(1 for f in result.findings if f.severity == Severity.MEDIUM)
    low = sum(1 for f in result.findings if f.severity == Severity.LOW)
    total = len(result.findings)

    if total == 0:
        return "## depfence Security Scan\n\n:white_check_mark: **No security issues found.**\n"

    status_emoji = ":x:" if critical > 0 else ":warning:" if high > 0 else ":large_orange_diamond:"
    status_text = "CRITICAL" if critical > 0 else "WARN" if high > 0 else "INFO"

    lines = [
        f"## depfence Security Scan — {status_emoji} {status_text}",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| :red_circle: Critical | {critical} |",
        f"| :orange_circle: High | {high} |",
        f"| :yellow_circle: Medium | {medium} |",
        f"| :white_circle: Low | {low} |",
        "",
        f"**{result.packages_scanned}** packages scanned, **{total}** findings.",
        "",
    ]

    if diff_info:
        added = diff_info.get("added", 0)
        if added:
            lines.append(f":new: **{added} new dependencies** added in this PR.")
            lines.append("")

    if critical + high > 0:
        lines.append("<details>")
        lines.append(f"<summary>Top findings ({min(critical + high, 10)} shown)</summary>")
        lines.append("")
        lines.append("| Package | Severity | Issue |")
        lines.append("|---------|----------|-------|")
        top = [f for f in result.findings if f.severity in (Severity.CRITICAL, Severity.HIGH)][:10]
        for f in top:
            sev = f":red_circle: {f.severity.name}" if f.severity == Severity.CRITICAL else f":orange_circle: {f.severity.name}"
            lines.append(f"| `{f.package}` | {sev} | {f.title} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if any(f.fix_version for f in result.findings):
        fixable = [f for f in result.findings if f.fix_version]
        lines.append(f":wrench: **{len(fixable)} findings** have auto-fix available. Run `depfence fix --apply`.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [depfence](https://github.com/ericrihm/depfence)*")

    return "\n".join(lines)
