"""GitHub PR annotation — post inline comments with dependency risk info.

Used in CI to annotate PRs with security findings for each changed dependency.
Requires GITHUB_TOKEN environment variable with appropriate permissions.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

from depfence.core.models import Finding, ScanResult, Severity


def format_pr_comment(result: ScanResult, diff_info: dict | None = None) -> str:
    """Format scan results as a GitHub PR comment body."""
    critical = sum(1 for f in result.findings if f.severity == Severity.CRITICAL)
    high = sum(1 for f in result.findings if f.severity == Severity.HIGH)
    medium = sum(1 for f in result.findings if f.severity == Severity.MEDIUM)
    low = sum(1 for f in result.findings if f.severity == Severity.LOW)
    total = len(result.findings)

    if total == 0:
        return "## depfence Security Scan\n\n:white_check_mark: **No security issues found.**\n"

    status_emoji = ":x:" if critical > 0 else ":warning:" if high > 0 else ":large_orange_diamond:"
    status_text = "CRITICAL" if critical > 0 else "WARN" if high > 0 else "INFO"

    lines = [
        f"## depfence Security Scan — {status_emoji} {status_text}",
        "",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| :red_circle: Critical | {critical} |",
        f"| :orange_circle: High | {high} |",
        f"| :yellow_circle: Medium | {medium} |",
        f"| :white_circle: Low | {low} |",
        "",
        f"**{result.packages_scanned}** packages scanned, **{total}** findings.",
        "",
    ]

    if diff_info:
        added = diff_info.get("added", 0)
        if added:
            lines.append(f":new: **{added} new dependencies** added in this PR.")
            lines.append("")

    if critical + high > 0:
        lines.append("<details>")
        lines.append(f"<summary>Top findings ({min(critical + high, 10)} shown)</summary>")
        lines.append("")
        lines.append("| Package | Severity | Issue |")
        lines.append("|---------|----------|-------|")
        top = [f for f in result.findings if f.severity in (Severity.CRITICAL, Severity.HIGH)][:10]
        for f in top:
            sev = f":red_circle: {f.severity.name}" if f.severity == Severity.CRITICAL else f":orange_circle: {f.severity.name}"
            lines.append(f"| `{f.package}` | {sev} | {f.title} |")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    if any(f.fix_version for f in result.findings):
        fixable = [f for f in result.findings if f.fix_version]
        lines.append(f":wrench: **{len(fixable)} findings** have auto-fix available. Run `depfence fix --apply`.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [depfence](https://github.com/ericrihm/depfence)*")

    return "\n".join(lines)


def post_pr_comment(comment_body: str, pr_number: int | None = None) -> bool:
    """Post a comment to the current PR using gh CLI.

    Returns True on success, False if not in a PR context or gh unavailable.
    """
    if pr_number is None:
        pr_number = _detect_pr_number()
    if pr_number is None:
        return False

    try:
        result = subprocess.run(
            ["gh", "pr", "comment", str(pr_number), "--body", comment_body],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def post_pr_review(findings: list[Finding], lockfile_path: str, pr_number: int | None = None) -> bool:
    """Post an inline review with findings mapped to the lockfile diff."""
    if pr_number is None:
        pr_number = _detect_pr_number()
    if not pr_number or not findings:
        return False

    comments = []
    for f in findings[:20]:
        comments.append({
            "path": lockfile_path,
            "body": f"**[{f.severity.name}]** {f.title}\n\n{f.detail}",
            "line": 1,
        })

    review_body = json.dumps({
        "body": f"depfence found {len(findings)} issue(s) in dependency changes.",
        "event": "COMMENT",
        "comments": comments,
    })

    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{{owner}}/{{repo}}/pulls/{pr_number}/reviews",
             "--input", "-"],
            input=review_body,
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def _detect_pr_number() -> int | None:
    """Detect PR number from CI environment."""
    # GitHub Actions
    gh_ref = os.environ.get("GITHUB_REF", "")
    if "/pull/" in gh_ref:
        try:
            return int(gh_ref.split("/pull/")[1].split("/")[0])
        except (IndexError, ValueError):
            pass

    # GITHUB_EVENT_PATH
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    if event_path:
        try:
            event = json.loads(Path(event_path).read_text())
            pr = event.get("pull_request", {})
            if pr.get("number"):
                return pr["number"]
        except (json.JSONDecodeError, OSError):
            pass

    return None
